/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import java.io.*;

/**
 * ActivityuseraccountroleKey definition.
 *
 * Code generated by Apache Ignite Schema Import utility: 04/29/2016.
 */
public class ActivityuseraccountroleKey implements Serializable {
    /** */
    private static final long serialVersionUID = 0L;

    /** Value for activityId. */
    private long activityId;

    /** Value for useraccountroleId. */
    private long useraccountroleId;

    /**
     * Gets activityId.
     *
     * @return Value for activityId.
     */
    public long getActivityId() {
        return activityId;
    }

    /**
     * Sets activityId.
     *
     * @param activityId New value for activityId.
     */
    public void setActivityId(long activityId) {
        this.activityId = activityId;
    }

    /**
     * Gets useraccountroleId.
     *
     * @return Value for useraccountroleId.
     */
    public long getUseraccountroleId() {
        return useraccountroleId;
    }

    /**
     * Sets useraccountroleId.
     *
     * @param useraccountroleId New value for useraccountroleId.
     */
    public void setUseraccountroleId(long useraccountroleId) {
        this.useraccountroleId = useraccountroleId;
    }

    /** {@inheritDoc} */
    @Override public boolean equals(Object o) {
        if (this == o)
            return true;

        if (!(o instanceof ActivityuseraccountroleKey))
            return false;

        ActivityuseraccountroleKey that = (ActivityuseraccountroleKey)o;

        if (activityId != that.activityId)
            return false;

        if (useraccountroleId != that.useraccountroleId)
            return false;

        return true;
    }

    /** {@inheritDoc} */
    @Override public int hashCode() {
        int res = (int)(activityId ^ (activityId >>> 32));

        res = 31 * res + (int)(useraccountroleId ^ (useraccountroleId >>> 32));

        return res;
    }

    /** {@inheritDoc} */
    @Override public String toString() {
        return "ActivityuseraccountroleKey [activityId=" + activityId +
            ", useraccountroleId=" + useraccountroleId +
            "]";
    }
}

