/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import java.io.Serializable;

import org.apache.ignite.cache.query.annotations.QuerySqlField;

/**
 * Activity definition.
 *
 * Code generated by Apache Ignite Schema Import utility: 04/29/2016.
 */
public class Activity implements Serializable {
    /** */
    private static final long serialVersionUID = 0L;

    /** Value for activityId. */
    @QuerySqlField(orderedGroups={@QuerySqlField.Group(name = "Activity_idx", order = 0)})
    private long activityId;

    /** Value for timestamp. */
    private String timestamp;

    /** Value for containerId. */
    private Long containerId;

    /** Value for activitytypeId. */
    private Long activitytypeId;

    /** Value for realizationId. */
    @QuerySqlField(orderedGroups={@QuerySqlField.Group(name = "Activity_idx", order = 1)})
    private Long realizationId;

    /** Value for kernelId. */
    @QuerySqlField(orderedGroups={@QuerySqlField.Group(name = "Activity_idx", order = 2)})
    private Long kernelId;

    /** Value for predecessortypeEnumid. */
    private long predecessortypeEnumid;

    /** Value for successortypeEnumid. */
    private long successortypeEnumid;

    /** Value for durationunitEnumid. */
    private Long durationunitEnumid;

    /** Value for name. */
    private String name;

    /** Value for nameMlid. */
    private Long nameMlid;

    /** Value for description. */
    private String description;

    /** Value for descriptionMlid. */
    private Long descriptionMlid;

    /** Value for duration. */
    private Double duration;

    /** Value for required. */
    private boolean required;

    /** Value for estimstartdate. */
    private java.sql.Date estimstartdate;

    /** Value for estimstarthour. */
    private Short estimstarthour;

    /** Value for estimendhour. */
    private Short estimendhour;

    /** Value for estimenddate. */
    private java.sql.Date estimenddate;

    /** Value for removefromworklist. */
    @QuerySqlField(orderedGroups={@QuerySqlField.Group(name = "Activity_idx", order = 3)})
    private boolean removefromworklist;

    /** Value for sequencenr. */
    private short sequencenr;

    /** Value for sessionId. */
    private Long sessionId;

    /** Value for lastactivityId. */
    @QuerySqlField(orderedGroups={@QuerySqlField.Group(name = "Activity_idx", order = 4)})
    private Long lastactivityId;

    /** Value for sysrepoperationId. */
    private Long sysrepoperationId;

    /** Value for lifecyclereporting. */
    private Boolean lifecyclereporting;

    /** Value for duedate. */
    private java.sql.Date duedate;

    /** Value for priorityEnumid. */
    private Long priorityEnumid;

    /** Value for notify. */
    private Boolean notify;

    /**
     * Gets activityId.
     *
     * @return Value for activityId.
     */
    public long getActivityId() {
        return activityId;
    }

    /**
     * Sets activityId.
     *
     * @param activityId New value for activityId.
     */
    public void setActivityId(long activityId) {
        this.activityId = activityId;
    }

    /**
     * Gets timestamp.
     *
     * @return Value for timestamp.
     */
    public String getTimestamp() {
        return timestamp;
    }

    /**
     * Sets timestamp.
     *
     * @param timestamp New value for timestamp.
     */
    public void setTimestamp(String timestamp) {
        this.timestamp = timestamp;
    }

    /**
     * Gets containerId.
     *
     * @return Value for containerId.
     */
    public Long getContainerId() {
        return containerId;
    }

    /**
     * Sets containerId.
     *
     * @param containerId New value for containerId.
     */
    public void setContainerId(Long containerId) {
        this.containerId = containerId;
    }

    /**
     * Gets activitytypeId.
     *
     * @return Value for activitytypeId.
     */
    public Long getActivitytypeId() {
        return activitytypeId;
    }

    /**
     * Sets activitytypeId.
     *
     * @param activitytypeId New value for activitytypeId.
     */
    public void setActivitytypeId(Long activitytypeId) {
        this.activitytypeId = activitytypeId;
    }

    /**
     * Gets realizationId.
     *
     * @return Value for realizationId.
     */
    public Long getRealizationId() {
        return realizationId;
    }

    /**
     * Sets realizationId.
     *
     * @param realizationId New value for realizationId.
     */
    public void setRealizationId(Long realizationId) {
        this.realizationId = realizationId;
    }

    /**
     * Gets kernelId.
     *
     * @return Value for kernelId.
     */
    public Long getKernelId() {
        return kernelId;
    }

    /**
     * Sets kernelId.
     *
     * @param kernelId New value for kernelId.
     */
    public void setKernelId(Long kernelId) {
        this.kernelId = kernelId;
    }

    /**
     * Gets predecessortypeEnumid.
     *
     * @return Value for predecessortypeEnumid.
     */
    public long getPredecessortypeEnumid() {
        return predecessortypeEnumid;
    }

    /**
     * Sets predecessortypeEnumid.
     *
     * @param predecessortypeEnumid New value for predecessortypeEnumid.
     */
    public void setPredecessortypeEnumid(long predecessortypeEnumid) {
        this.predecessortypeEnumid = predecessortypeEnumid;
    }

    /**
     * Gets successortypeEnumid.
     *
     * @return Value for successortypeEnumid.
     */
    public long getSuccessortypeEnumid() {
        return successortypeEnumid;
    }

    /**
     * Sets successortypeEnumid.
     *
     * @param successortypeEnumid New value for successortypeEnumid.
     */
    public void setSuccessortypeEnumid(long successortypeEnumid) {
        this.successortypeEnumid = successortypeEnumid;
    }

    /**
     * Gets durationunitEnumid.
     *
     * @return Value for durationunitEnumid.
     */
    public Long getDurationunitEnumid() {
        return durationunitEnumid;
    }

    /**
     * Sets durationunitEnumid.
     *
     * @param durationunitEnumid New value for durationunitEnumid.
     */
    public void setDurationunitEnumid(Long durationunitEnumid) {
        this.durationunitEnumid = durationunitEnumid;
    }

    /**
     * Gets name.
     *
     * @return Value for name.
     */
    public String getName() {
        return name;
    }

    /**
     * Sets name.
     *
     * @param name New value for name.
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Gets nameMlid.
     *
     * @return Value for nameMlid.
     */
    public Long getNameMlid() {
        return nameMlid;
    }

    /**
     * Sets nameMlid.
     *
     * @param nameMlid New value for nameMlid.
     */
    public void setNameMlid(Long nameMlid) {
        this.nameMlid = nameMlid;
    }

    /**
     * Gets description.
     *
     * @return Value for description.
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets description.
     *
     * @param description New value for description.
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * Gets descriptionMlid.
     *
     * @return Value for descriptionMlid.
     */
    public Long getDescriptionMlid() {
        return descriptionMlid;
    }

    /**
     * Sets descriptionMlid.
     *
     * @param descriptionMlid New value for descriptionMlid.
     */
    public void setDescriptionMlid(Long descriptionMlid) {
        this.descriptionMlid = descriptionMlid;
    }

    /**
     * Gets duration.
     *
     * @return Value for duration.
     */
    public Double getDuration() {
        return duration;
    }

    /**
     * Sets duration.
     *
     * @param duration New value for duration.
     */
    public void setDuration(Double duration) {
        this.duration = duration;
    }

    /**
     * Gets required.
     *
     * @return Value for required.
     */
    public boolean getRequired() {
        return required;
    }

    /**
     * Sets required.
     *
     * @param required New value for required.
     */
    public void setRequired(boolean required) {
        this.required = required;
    }

    /**
     * Gets estimstartdate.
     *
     * @return Value for estimstartdate.
     */
    public java.sql.Date getEstimstartdate() {
        return estimstartdate;
    }

    /**
     * Sets estimstartdate.
     *
     * @param estimstartdate New value for estimstartdate.
     */
    public void setEstimstartdate(java.sql.Date estimstartdate) {
        this.estimstartdate = estimstartdate;
    }

    /**
     * Gets estimstarthour.
     *
     * @return Value for estimstarthour.
     */
    public Short getEstimstarthour() {
        return estimstarthour;
    }

    /**
     * Sets estimstarthour.
     *
     * @param estimstarthour New value for estimstarthour.
     */
    public void setEstimstarthour(Short estimstarthour) {
        this.estimstarthour = estimstarthour;
    }

    /**
     * Gets estimendhour.
     *
     * @return Value for estimendhour.
     */
    public Short getEstimendhour() {
        return estimendhour;
    }

    /**
     * Sets estimendhour.
     *
     * @param estimendhour New value for estimendhour.
     */
    public void setEstimendhour(Short estimendhour) {
        this.estimendhour = estimendhour;
    }

    /**
     * Gets estimenddate.
     *
     * @return Value for estimenddate.
     */
    public java.sql.Date getEstimenddate() {
        return estimenddate;
    }

    /**
     * Sets estimenddate.
     *
     * @param estimenddate New value for estimenddate.
     */
    public void setEstimenddate(java.sql.Date estimenddate) {
        this.estimenddate = estimenddate;
    }

    /**
     * Gets removefromworklist.
     *
     * @return Value for removefromworklist.
     */
    public boolean getRemovefromworklist() {
        return removefromworklist;
    }

    /**
     * Sets removefromworklist.
     *
     * @param removefromworklist New value for removefromworklist.
     */
    public void setRemovefromworklist(boolean removefromworklist) {
        this.removefromworklist = removefromworklist;
    }

    /**
     * Gets sequencenr.
     *
     * @return Value for sequencenr.
     */
    public short getSequencenr() {
        return sequencenr;
    }

    /**
     * Sets sequencenr.
     *
     * @param sequencenr New value for sequencenr.
     */
    public void setSequencenr(short sequencenr) {
        this.sequencenr = sequencenr;
    }

    /**
     * Gets sessionId.
     *
     * @return Value for sessionId.
     */
    public Long getSessionId() {
        return sessionId;
    }

    /**
     * Sets sessionId.
     *
     * @param sessionId New value for sessionId.
     */
    public void setSessionId(Long sessionId) {
        this.sessionId = sessionId;
    }

    /**
     * Gets lastactivityId.
     *
     * @return Value for lastactivityId.
     */
    public Long getLastactivityId() {
        return lastactivityId;
    }

    /**
     * Sets lastactivityId.
     *
     * @param lastactivityId New value for lastactivityId.
     */
    public void setLastactivityId(Long lastactivityId) {
        this.lastactivityId = lastactivityId;
    }

    /**
     * Gets sysrepoperationId.
     *
     * @return Value for sysrepoperationId.
     */
    public Long getSysrepoperationId() {
        return sysrepoperationId;
    }

    /**
     * Sets sysrepoperationId.
     *
     * @param sysrepoperationId New value for sysrepoperationId.
     */
    public void setSysrepoperationId(Long sysrepoperationId) {
        this.sysrepoperationId = sysrepoperationId;
    }

    /**
     * Gets lifecyclereporting.
     *
     * @return Value for lifecyclereporting.
     */
    public Boolean getLifecyclereporting() {
        return lifecyclereporting;
    }

    /**
     * Sets lifecyclereporting.
     *
     * @param lifecyclereporting New value for lifecyclereporting.
     */
    public void setLifecyclereporting(Boolean lifecyclereporting) {
        this.lifecyclereporting = lifecyclereporting;
    }

    /**
     * Gets duedate.
     *
     * @return Value for duedate.
     */
    public java.sql.Date getDuedate() {
        return duedate;
    }

    /**
     * Sets duedate.
     *
     * @param duedate New value for duedate.
     */
    public void setDuedate(java.sql.Date duedate) {
        this.duedate = duedate;
    }

    /**
     * Gets priorityEnumid.
     *
     * @return Value for priorityEnumid.
     */
    public Long getPriorityEnumid() {
        return priorityEnumid;
    }

    /**
     * Sets priorityEnumid.
     *
     * @param priorityEnumid New value for priorityEnumid.
     */
    public void setPriorityEnumid(Long priorityEnumid) {
        this.priorityEnumid = priorityEnumid;
    }

    /**
     * Gets notify.
     *
     * @return Value for notify.
     */
    public Boolean getNotify() {
        return notify;
    }

    /**
     * Sets notify.
     *
     * @param notify New value for notify.
     */
    public void setNotify(Boolean notify) {
        this.notify = notify;
    }

    /** {@inheritDoc} */
    @Override public boolean equals(Object o) {
        if (this == o)
            return true;

        if (!(o instanceof Activity))
            return false;

        Activity that = (Activity)o;

        if (activityId != that.activityId)
            return false;

        if (timestamp != null ? !timestamp.equals(that.timestamp) : that.timestamp != null)
            return false;

        if (containerId != null ? !containerId.equals(that.containerId) : that.containerId != null)
            return false;

        if (activitytypeId != null ? !activitytypeId.equals(that.activitytypeId) : that.activitytypeId != null)
            return false;

        if (realizationId != null ? !realizationId.equals(that.realizationId) : that.realizationId != null)
            return false;

        if (kernelId != null ? !kernelId.equals(that.kernelId) : that.kernelId != null)
            return false;

        if (predecessortypeEnumid != that.predecessortypeEnumid)
            return false;

        if (successortypeEnumid != that.successortypeEnumid)
            return false;

        if (durationunitEnumid != null ? !durationunitEnumid.equals(that.durationunitEnumid) : that.durationunitEnumid != null)
            return false;

        if (name != null ? !name.equals(that.name) : that.name != null)
            return false;

        if (nameMlid != null ? !nameMlid.equals(that.nameMlid) : that.nameMlid != null)
            return false;

        if (description != null ? !description.equals(that.description) : that.description != null)
            return false;

        if (descriptionMlid != null ? !descriptionMlid.equals(that.descriptionMlid) : that.descriptionMlid != null)
            return false;

        if (duration != null ? !duration.equals(that.duration) : that.duration != null)
            return false;

        if (required != that.required)
            return false;

        if (estimstartdate != null ? !estimstartdate.equals(that.estimstartdate) : that.estimstartdate != null)
            return false;

        if (estimstarthour != null ? !estimstarthour.equals(that.estimstarthour) : that.estimstarthour != null)
            return false;

        if (estimendhour != null ? !estimendhour.equals(that.estimendhour) : that.estimendhour != null)
            return false;

        if (estimenddate != null ? !estimenddate.equals(that.estimenddate) : that.estimenddate != null)
            return false;

        if (removefromworklist != that.removefromworklist)
            return false;

        if (sequencenr != that.sequencenr)
            return false;

        if (sessionId != null ? !sessionId.equals(that.sessionId) : that.sessionId != null)
            return false;

        if (lastactivityId != null ? !lastactivityId.equals(that.lastactivityId) : that.lastactivityId != null)
            return false;

        if (sysrepoperationId != null ? !sysrepoperationId.equals(that.sysrepoperationId) : that.sysrepoperationId != null)
            return false;

        if (lifecyclereporting != null ? !lifecyclereporting.equals(that.lifecyclereporting) : that.lifecyclereporting != null)
            return false;

        if (duedate != null ? !duedate.equals(that.duedate) : that.duedate != null)
            return false;

        if (priorityEnumid != null ? !priorityEnumid.equals(that.priorityEnumid) : that.priorityEnumid != null)
            return false;

        if (notify != null ? !notify.equals(that.notify) : that.notify != null)
            return false;

        return true;
    }

    /** {@inheritDoc} */
    @Override public int hashCode() {
        int res = (int)(activityId ^ (activityId >>> 32));

        res = 31 * res + (timestamp != null ? timestamp.hashCode() : 0);

        res = 31 * res + (containerId != null ? containerId.hashCode() : 0);

        res = 31 * res + (activitytypeId != null ? activitytypeId.hashCode() : 0);

        res = 31 * res + (realizationId != null ? realizationId.hashCode() : 0);

        res = 31 * res + (kernelId != null ? kernelId.hashCode() : 0);

        res = 31 * res + (int)(predecessortypeEnumid ^ (predecessortypeEnumid >>> 32));

        res = 31 * res + (int)(successortypeEnumid ^ (successortypeEnumid >>> 32));

        res = 31 * res + (durationunitEnumid != null ? durationunitEnumid.hashCode() : 0);

        res = 31 * res + (name != null ? name.hashCode() : 0);

        res = 31 * res + (nameMlid != null ? nameMlid.hashCode() : 0);

        res = 31 * res + (description != null ? description.hashCode() : 0);

        res = 31 * res + (descriptionMlid != null ? descriptionMlid.hashCode() : 0);

        res = 31 * res + (duration != null ? duration.hashCode() : 0);

        res = 31 * res + (required ? 1 : 0);

        res = 31 * res + (estimstartdate != null ? estimstartdate.hashCode() : 0);

        res = 31 * res + (estimstarthour != null ? estimstarthour.hashCode() : 0);

        res = 31 * res + (estimendhour != null ? estimendhour.hashCode() : 0);

        res = 31 * res + (estimenddate != null ? estimenddate.hashCode() : 0);

        res = 31 * res + (removefromworklist ? 1 : 0);

        res = 31 * res + (int)sequencenr;

        res = 31 * res + (sessionId != null ? sessionId.hashCode() : 0);

        res = 31 * res + (lastactivityId != null ? lastactivityId.hashCode() : 0);

        res = 31 * res + (sysrepoperationId != null ? sysrepoperationId.hashCode() : 0);

        res = 31 * res + (lifecyclereporting != null ? lifecyclereporting.hashCode() : 0);

        res = 31 * res + (duedate != null ? duedate.hashCode() : 0);

        res = 31 * res + (priorityEnumid != null ? priorityEnumid.hashCode() : 0);

        res = 31 * res + (notify != null ? notify.hashCode() : 0);

        return res;
    }

    /** {@inheritDoc} */
    @Override public String toString() {
        return "Activity [activityId=" + activityId +
            ", timestamp=" + timestamp +
            ", containerId=" + containerId +
            ", activitytypeId=" + activitytypeId +
            ", realizationId=" + realizationId +
            ", kernelId=" + kernelId +
            ", predecessortypeEnumid=" + predecessortypeEnumid +
            ", successortypeEnumid=" + successortypeEnumid +
            ", durationunitEnumid=" + durationunitEnumid +
            ", name=" + name +
            ", nameMlid=" + nameMlid +
            ", description=" + description +
            ", descriptionMlid=" + descriptionMlid +
            ", duration=" + duration +
            ", required=" + required +
            ", estimstartdate=" + estimstartdate +
            ", estimstarthour=" + estimstarthour +
            ", estimendhour=" + estimendhour +
            ", estimenddate=" + estimenddate +
            ", removefromworklist=" + removefromworklist +
            ", sequencenr=" + sequencenr +
            ", sessionId=" + sessionId +
            ", lastactivityId=" + lastactivityId +
            ", sysrepoperationId=" + sysrepoperationId +
            ", lifecyclereporting=" + lifecyclereporting +
            ", duedate=" + duedate +
            ", priorityEnumid=" + priorityEnumid +
            ", notify=" + notify +
            "]";
    }
}

