/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import java.io.*;

import org.apache.ignite.cache.query.annotations.QuerySqlField;

/**
 * Activityhistoryuseraccount definition.
 *
 * Code generated by Apache Ignite Schema Import utility: 04/29/2016.
 */
public class Activityhistoryuseraccount implements Serializable {
    /** */
    private static final long serialVersionUID = 0L;

    /** Value for useraccountId. */
    @QuerySqlField()
    private long useraccountId;

    /** Value for activityhistoryId. */
    @QuerySqlField(orderedGroups={@QuerySqlField.Group(name = "Activityhistoryuseraccount_idx", order = 0)})
    private long activityhistoryId;

    /**
     * Gets useraccountId.
     *
     * @return Value for useraccountId.
     */
    public long getUseraccountId() {
        return useraccountId;
    }

    /**
     * Sets useraccountId.
     *
     * @param useraccountId New value for useraccountId.
     */
    public void setUseraccountId(long useraccountId) {
        this.useraccountId = useraccountId;
    }

    /**
     * Gets activityhistoryId.
     *
     * @return Value for activityhistoryId.
     */
    public long getActivityhistoryId() {
        return activityhistoryId;
    }

    /**
     * Sets activityhistoryId.
     *
     * @param activityhistoryId New value for activityhistoryId.
     */
    public void setActivityhistoryId(long activityhistoryId) {
        this.activityhistoryId = activityhistoryId;
    }

    /** {@inheritDoc} */
    @Override public boolean equals(Object o) {
        if (this == o)
            return true;

        if (!(o instanceof Activityhistoryuseraccount))
            return false;

        Activityhistoryuseraccount that = (Activityhistoryuseraccount)o;

        if (useraccountId != that.useraccountId)
            return false;

        if (activityhistoryId != that.activityhistoryId)
            return false;

        return true;
    }

    /** {@inheritDoc} */
    @Override public int hashCode() {
        int res = (int)(useraccountId ^ (useraccountId >>> 32));

        res = 31 * res + (int)(activityhistoryId ^ (activityhistoryId >>> 32));

        return res;
    }

    /** {@inheritDoc} */
    @Override public String toString() {
        return "Activityhistoryuseraccount [useraccountId=" + useraccountId +
            ", activityhistoryId=" + activityhistoryId +
            "]";
    }
}

